services:

  async-crawler:
    image: async-crawler:latest
    container_name: async-crawler
    hostname: "async-crawler"
    depends_on:
      - cache
    build:
        dockerfile: Dockerfile
        target: production
        context: .

  cache:
    image: redis:7.0-alpine
    ports:
      - '6379:6379'
    environment:
      - REDIS_PORT=6379
    volumes: 
      - cache:/data

volumes:
  cache:

